server:
  port: 8081
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/smbms?serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

      druid:
        aop-patterns: com.vayber.*  #监控SpringBean
        filters: stat,wall    # 底层开启功能，stat（sql监控），wall（防火墙）

        filter:         # 对上面filters里面的stat的详细配置
          stat:
            slow-sql-millis: 1000   #慢sql
            logSlowSql: true        #慢sql记录
            enabled: true           #开启
          wall:
            enabled: true           #开启
            config:                 #配置
              drop-table-allow: false     #不允许删表


        stat-view-servlet:   # 配置监控页功能
          enabled: true       #开启
          login-username: admin   #登录用户名
          login-password: 123456  #登录密码
          reset-enable: false     #重置按钮

        web-stat-filter:      # 监控web
          enabled: true       #开启
          url-pattern: /*     #监控哪些
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'   #排除哪些

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

  mapper-locations: classpath:mapper/*.xml


